@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

### Route GET /users
GET {{baseUrl}}/users

### Route GET /members
GET {{baseUrl}}/members

### Route GET /members/{id}
GET {{baseUrl}}/members/1

### Route GET /coachs
GET {{baseUrl}}/coachs

### Route GET /coach/{id}/bookings
GET {{baseUrl}}/coach/7/bookings

### Route GET /coach/{id}/next-bookings
GET {{baseUrl}}/coach/7/next-bookings

### Route GET /coach/{id}/last-bookings
GET {{baseUrl}}/coach/7/last-bookings