@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

### Récupérer tous le users
GET {{baseUrl}}/users

### Récupérer tous les adhérents
GET {{baseUrl}}/members

### Récupérer un adhérent
GET {{baseUrl}}/members/100

### Récupérer tous les coachs
GET {{baseUrl}}/coachs

### Route GET /member/{id}/workouts
GET {{baseUrl}}/members/3/workouts

### Route GET /coach/{id}+specialty
GET {{baseUrl}}/coachs/6

### Route GET /coach/{id}/bookings
GET {{baseUrl}}/coachs/7/bookings

### Route GET /coach/{id}/next-bookings
GET {{baseUrl}}/coachs/7/next-bookings

### Route GET /coach/{id}/last-bookings
GET {{baseUrl}}/coachs/7/last-bookings

### Ajouter new User
POST {{baseUrl}}/new-user
Content-Type: application/json

{
    "firstname": "Nouveau",
    "lastname": "User",
    "email": "nouveau@gmail.com",
    "role": "MEMBER"
}

### Set new UPassword
POST {{baseUrl}}/new-password
Content-Type: application/json

{
    "email": "nouveau@gmail.com",
    "password": "test",
    "confirm": "test"
}

### Connexion
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "nouveau@gmail.com",
    "password": "test"
}