@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@baseUrl = {{protocol}}://{{domainname}}:{{port}}

### Récupérer tous le users
GET {{baseUrl}}/users

### Récupérer tous les adhérents
GET {{baseUrl}}/members

### Récupérer un adhérent
GET {{baseUrl}}/members/1

### Récupérer tous les coachs
GET {{baseUrl}}/coachs

### Récupérer toutes les résevations d'un coach
GET {{baseUrl}}/coach/7/bookings

### Récupérer toutes les prochaines réservations d'un coach
GET {{baseUrl}}/coach/7/next-bookings

### Récupérer toutes les réservations passées d'un coach
GET {{baseUrl}}/coach/7/last-bookings

### Ajouter des créneaux coaching 

POST {{baseUrl}}/new-coachings
Content-Type: application/json

{
    "date": "2021-04-01",
    "startTime": "10:00:00",
    "endTime": "11:00:00",
    "coachId": 7
}