@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/api-v1

# https://app-osport.herokuapp.com/api-v1

//{{protocol}}://{{domainname}}:{{port}}/api-v1

//snkcmuclyjjrag:e460879da3dc3d10454bd6031a1f3887e8c2be23ad5911e352e49feca6da5fd8@ec2-176-34-222-188.eu-west-1.compute.amazonaws.com:5432/daindlp1mpsoct

// URL pour sqitch deploy et revert sur URL heroku


##################################################################################
#################################### CONNEXION ###################################
##################################################################################


### DÉFINIR UN NOUVEAU MOT DE PASSE
POST {{baseUrl}}/register?token=78c4eaa7-b8b2-419b-aca0-c04c3370c118
Content-Type: application/json

{
    "password": "1Aaaaaaa!",
    "confirm": "1Aaaaaaa!"
}

### MOT DE PASSE OUBLIÉ
POST {{baseUrl}}/forgotten-password
Content-Type: application/json

{
    "email": "contact@hogwarts.com"
}

### ENVOYER SES INFORMATIONS DE CONNEXION 
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "dario@oclock.io",
    "password":"1Aaaaaaa!"
}




##################################################################################
########################## FONTCIONS POSSIBLES MEMBERS ###########################
##################################################################################


////////// WORKOUTS & HEALTH DATA \\\\\\\\\\
//-----------------------------------------\\


### AJOUTER UN WORKOUT + HEALTH DATA
POST {{baseUrl}}/new-workout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNjA2NTMzNiwiZXhwIjoxNjE2MTAxMzM2fQ.gfyI06fucicVGacfixUhR9OW-0y8f1voMZP4yvVmfXI

{
    "date": "2021-03-12",
    "content": "test nouveau workout",
    "weight": 80,
    "muscleMass": 85,
    "fatMass": 10,
    "boneMass": 5,
    "bodyWater": 59
}


### RÉCUPÉRER TOUS LES WORKOUTS PAR ORDRE DÉCROISSANT 
GET {{baseUrl}}/workouts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNjA2NDg2NiwiZXhwIjoxNjE2MTAwODY2fQ.7lej6Ti3N4FbvlxLFABh76T0t5ZqC_Eil9o67ETUQ3M


### RÉCUPÉRER TOUS LES ENREGISTREMENTS SANTÉ 
GET {{baseUrl}}/health
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNjA2NDg2NiwiZXhwIjoxNjE2MTAwODY2fQ.7lej6Ti3N4FbvlxLFABh76T0t5ZqC_Eil9o67ETUQ3M


### MODIFIER UN WORKOUT ET SES DONNÉES SANTÉ
PATCH {{baseUrl}}/edit-workout/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiQWxBQkFTQGdtYWlsLmNvbSIsInJvbGUiOiJNRU1CRVIiLCJpYXQiOjE2MTYxNDcwNTMsImV4cCI6MTYxNjE4MzA1M30.8yl3-R2CTzZ1Ds_L-PZUInejSzMmPYRDYb1IeOxgvjA

{
    "date": "2021-03-11",
    "content": "Workout modifié bis ",
    "weight": 84,
    "muscleMass": 9,
    "fatMass": 9,
    "boneMass": 9,
    "bodyWater": 9
}


### SUPPRIMER UN WORKOUT ET LES DONNÉES SANTÉ ASSOCIÉES
DELETE {{baseUrl}}/delete-workout/500
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiQWxBQkFTQGdtYWlsLmNvbSIsInJvbGUiOiJNRU1CRVIiLCJpYXQiOjE2MTYxNDcwNTMsImV4cCI6MTYxNjE4MzA1M30.8yl3-R2CTzZ1Ds_L-PZUInejSzMmPYRDYb1IeOxgvjA


////////// COACHINGS \\\\\\\\\\
//----------------------------\\


### RÉCUPÉRER TOUS LES COACHINGS DISPONIBLES À UNE DATE
GET {{baseUrl}}/available-coachings?date=2021-04-05
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNjA2NDg2NiwiZXhwIjoxNjE2MTAwODY2fQ.7lej6Ti3N4FbvlxLFABh76T0t5ZqC_Eil9o67ETUQ3M


### RÉCUPÉRER LES PROCHAINS COACHINGS PRÉVUS 
GET {{baseUrl}}/member-next-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNjA2NDg2NiwiZXhwIjoxNjE2MTAwODY2fQ.7lej6Ti3N4FbvlxLFABh76T0t5ZqC_Eil9o67ETUQ3M


### RÉSERVER UN COACHING (update)
POST {{baseUrl}}/book-coaching
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNjA2NDg2NiwiZXhwIjoxNjE2MTAwODY2fQ.7lej6Ti3N4FbvlxLFABh76T0t5ZqC_Eil9o67ETUQ3M

{
    "coachingId": 88
}


### SUPPRIMER UNE RÉSERVATION (update) 
PATCH {{baseUrl}}/bookings/88/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM0LCJlbWFpbCI6ImFsZXh0QGNvYWNoLmNvbSIsInJvbGUiOiJDT0FDSCIsImlhdCI6MTYxNjA2NDg2NiwiZXhwIjoxNjE2MTAwODY2fQ.7lej6Ti3N4FbvlxLFABh76T0t5ZqC_Eil9o67ETUQ3M




##################################################################################
############################## FONCTIONS D'UN COACHS #############################
##################################################################################


////////// WORKOUTS & COMMENTAIRES \\\\\\\\\\
//------------------------------------------\\


### CRÉER UN COMMENTAIRE ASSOCIÉ AU WORKOUT D'UN ADHÉRENT
POST {{baseUrl}}/new-comment/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6ImZhYmllbkBlZGYuY29tIiwicm9sZSI6IkNPQUNIIiwiaWF0IjoxNjE2MTQ4ODQwLCJleHAiOjE2MTYxODQ4NDB9.m_v5h2yh3Y4Lw5Mh-8p9VopuS88oErK6gpNM407-_AE

{
    "content": "test commentaire aaaaa"
}


### MODIFIER UN COMMENTAIRE
PATCH {{baseUrl}}/edit-comment/141
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6ImZhYmllbkBlZGYuY29tIiwicm9sZSI6IkNPQUNIIiwiaWF0IjoxNjE2MTQ4ODQwLCJleHAiOjE2MTYxODQ4NDB9.m_v5h2yh3Y4Lw5Mh-8p9VopuS88oErK6gpNM407-_AE

{
    "content": "Nouveau comment modifié."
}


### SUPPRIMER UN COMMENTAIRE
DELETE {{baseUrl}}/delete-comment/141
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6ImZhYmllbkBlZGYuY29tIiwicm9sZSI6IkNPQUNIIiwiaWF0IjoxNjE2MTQ4ODQwLCJleHAiOjE2MTYxODQ4NDB9.m_v5h2yh3Y4Lw5Mh-8p9VopuS88oErK6gpNM407-_AE


////////// COACHINGS \\\\\\\\\\
//----------------------------\\


### RÉCUPÉRER SES PROCHAINS RDV COACHING
GET {{baseUrl}}/coach-next-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiY29udGFjdEBob2d3YXJ0cy5jb20iLCJyb2xlIjoiQ09BQ0giLCJpYXQiOjE2MTYxNDk2ODIsImV4cCI6MTYxNjE4NTY4Mn0.8sH6DM3dBRvGp7cLAnenBcDjXRpKhhr-SfKi5rhjm7s


### RÉCUPÉRER SES RDV COACHING PASSÉS
GET {{baseUrl}}/coach-last-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiY29udGFjdEBob2d3YXJ0cy5jb20iLCJyb2xlIjoiQ09BQ0giLCJpYXQiOjE2MTYxNDk2ODIsImV4cCI6MTYxNjE4NTY4Mn0.8sH6DM3dBRvGp7cLAnenBcDjXRpKhhr-SfKi5rhjm7s


### RÉCUPÉRER LES PROCHAINS RDV COACHING D'UN ADHÉRENT
GET {{baseUrl}}/members/1123/next-bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiY29udGFjdEBob2d3YXJ0cy5jb20iLCJyb2xlIjoiQ09BQ0giLCJpYXQiOjE2MTYxNDk2ODIsImV4cCI6MTYxNjE4NTY4Mn0.8sH6DM3dBRvGp7cLAnenBcDjXRpKhhr-SfKi5rhjm7s


////////// ADHÉRENTS \\\\\\\\\\
//----------------------------\\


### RÉCUPÉRER TOUS LES ADHÉRENTS
GET {{baseUrl}}/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiY29udGFjdEBob2d3YXJ0cy5jb20iLCJyb2xlIjoiQ09BQ0giLCJpYXQiOjE2MTYxNDk2ODIsImV4cCI6MTYxNjE4NTY4Mn0.8sH6DM3dBRvGp7cLAnenBcDjXRpKhhr-SfKi5rhjm7s




##################################################################################
############################# FONCTIONS POUR MANAGER #############################
##################################################################################


////////// SPÉCIALITÉS \\\\\\\\\\
//------------------------------\\


### AJOUTER UNE SPÉCIALITÉ
POST {{baseUrl}}/specialties
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4

{
    "name": "NEWSpébis"
}


### RÉCUPÉRER TOUTES LES SPÉCIALITÉS
GET {{baseUrl}}/specialties
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4


### SUPPRIMER UNE SPÉCIALITÉ
DELETE  {{baseUrl}}/specialties/33
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4


////////// USERS \\\\\\\\\\
//------------------------\\


### AJOUTER UN ADHÉRENT
POST {{baseUrl}}/new-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4

{
    "firstname": "test",
    "lastname": "testssss",
    "email": "nouveauval@toto.com",
    "role": "MEMBER"
}


### AJOUTER UN COACH
POST {{baseUrl}}/new-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4

{
    "firstname": "bug",
    "lastname": "coachbis",
    "email": "aaazzsxxsaaaa@coach.com",
    "role": "COACH",
    "specialties": [1,3]
}


### RÉCUPÉRER UN ADHÉRENT
GET {{baseUrl}}/members/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4


### RÉCUPÉRER UN COACH
GET {{baseUrl}}/coachs/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4


### MODIFIER UN USER 
PATCH  {{baseUrl}}/users/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4

{
    "firstname": "Albus",
    "email": "contact@hogwarts.com",
    "specialties":[4,7, 1]
}


### SUPPRIMER UN USER
DELETE {{baseUrl}}/users/102
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4


////////// COACHINGS \\\\\\\\\\
//----------------------------\\


### AJOUTER DES CRÉNEAUX COACHING 
POST {{baseUrl}}/new-coachings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4

{
    "date": "2021-06-15",
    "start": "11:45",
    "end": "10:00",
    "coachId": 7
}

### RÉCUPÉRER TOUS LES COACHINGS  
GET {{baseUrl}}/coachings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4

### RÉCUPÉRER UN COACHING    
GET {{baseUrl}}/coaching/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4


### SUPPRIMER UN COACHING
DELETE {{baseUrl}}/coaching/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4




##################################################################################
############################## FONCTIONS TOUT LE MONDE ###########################
##################################################################################


### RÉCUPÉRER LES COACHS
GET {{baseUrl}}/coachs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJlbWFpbCI6ImRhcmlvQG9jbG9jay5pbyIsInJvbGUiOiJPV05FUiIsImlhdCI6MTYxNjE1MDEyNSwiZXhwIjoxNjE2MTg2MTI1fQ.QLTloCz7xPTFiB4Jdoa4dz_Y0YYrsi5JYG4qw_2h9Q4